### ISSUE TITLE
html파일에 호환성을 위한 xmlns:th 삭제

### ISSUE THREAD

**Issue by hegunhee** [hegunhee/fastcampus-project-board#21]
해당 이슈는 footer와 header에  설정되어있는 thymeleaf 설정을 제거합니다.
- [x] footer와 header의 xmlns:th="http://www.thymeleaf.org" 설정 제거

https://github.com/haeun1700/fastcampus-project-board/pull/16#discussion_r1803594918
해당 issue가 시작된곳

해당 작업을 진행하려 했으나
mikonu의 제품에는 이미 html파일에 xmls:th 구문이 삭제되었기 때문에 반영할 수 없었습니다.
해당 이슈는 19일 close 됩니다.

@mikonu

**Comment by mikonu** [comment]
네 그것은 @haeun1700 님 pr에서 등장한 것이기 때문에 리뷰를 드린 것일 뿐입니다. 원래 없다면 문제가 아니죠. 알아서 마무리해주시면 되겠습니다.

**Comment by hegunhee** [comment]
xmls:th="[http://www.thymeleaf.org."를](http://www.thymeleaf.org.xn--"-dl1f/) 뺀 코드를 재현해서 mikonu의 main-uno에 PR올리려고 했습니다만
현재 main-uno에는 이미 해당 xmls:th 코드가 빠져있어서 PR을 올릴 수 없습니다.

제 제품의 태그 제거 feature 브랜치에서 작업 후 mikonu의 제품에 PR을 올리려 했으나
제 제품 진척도와 mikonu의 제품 진척도가 다르기 때문에 changed files가 너무 많이 검출되었습니다.'
이렇게 될 경우 저희는 footer.html, header.html의 xmls:th 코드 제거만 보고싶은데
너무 많은 다른것들을 신경써야하므로 불편합니다.(물론 해당 파일만 검색해서 볼 수 있겠죠)

그래서 생각한 방법이 xmls:th 제거 작업 브랜치 <- mikonu의 제품 으로 머지를 받고
제거 작업 브랜치에서 xmls:th 제거를 한 후 다시 mikonu의 제품으로 PR을 올리려 했습니다.
(이렇게 할 경우 changed files가 저희가 보고싶었던 footer.html과 header.html만 남습니다.)

하지만 위에서 말씀드린것과 같이 mikonu의 제품은 이미 xmls:th 태그가 삭제되었기 때문에
해당 작업을 진행할 수 없습니다.

**Comment by hegunhee** [comment]
해당 이슈는 close하겠습니다.
